#DROP DATABASE ProyectoDS;
CREATE DATABASE ProyectoDS;
USE ProyectoDS;


CREATE TABLE TIPO_PAGO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(180)
);


CREATE TABLE BODEGA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DIRECCION VARCHAR(30),
    CIUDAD VARCHAR(30),
    PAIS VARCHAR(30),
    TELEFONO VARCHAR(10)
);
CREATE TABLE CATEGORIA(
	CATEGORIA VARCHAR(30),
    DESCRIPCION VARCHAR(220),
    PRIMARY KEY (CATEGORIA)
);

CREATE TABLE PRODUCTO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) UNIQUE,
    DESCRIPCION VARCHAR(30),
    PRECIO FLOAT,
    CATEGORIA VARCHAR(30),
    FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(CATEGORIA)
);

CREATE TABLE CLIENTE(
    CEDULA VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    EMAIL VARCHAR(30),
    DIRECCION VARCHAR(30)
);

CREATE TABLE LOCAL(
ID INT AUTO_INCREMENT PRIMARY KEY,
DIRECCION VARCHAR(30),
CIUDAD VARCHAR(30),
PAIS VARCHAR(30),
TELEFONO VARCHAR(10)

);



CREATE TABLE TIPO_USUARIO(
    TIPO_USUARIO VARCHAR(30),
    DESCRIPCION VARCHAR(220),
    PRIMARY KEY(TIPO_USUARIO)
);

CREATE TABLE USUARIOS(
	USERNAME VARCHAR(30) NOT NULL,
	CLAVE VARCHAR(30),
	TIPO_USUARIO VARCHAR(30),
	PRIMARY KEY (USERNAME),
	FOREIGN KEY (TIPO_USUARIO) REFERENCES TIPO_USUARIO(TIPO_USUARIO)
);

CREATE TABLE JEFE_BODEGA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    CEDULA VARCHAR(10),
    EMAIL VARCHAR(30),
    ID_BODEGA INT NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
    FOREIGN KEY (ID_BODEGA) REFERENCES BODEGA(ID)
);

CREATE TABLE VENDEDOR(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    CEDULA VARCHAR(10),
    EMAIL VARCHAR(30),
    ID_LOCAL INT NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
    FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL(ID)
);

CREATE TABLE ADMINISTRADOR(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    CEDULA VARCHAR(10),
    EMAIL VARCHAR(30),
    ID_LOCAL INT NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
    FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL(ID)
);

CREATE TABLE GERENTE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    CEDULA VARCHAR(10),
    EMAIL VARCHAR(30),
    ID_LOCAL INT NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
    FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL(ID)
);

CREATE TABLE REPARTIDOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	CEDULA VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(30),
	ID_JEFE_BODEGA INT NOT NULL,
	FOREIGN KEY (ID_JEFE_BODEGA) REFERENCES JEFE_BODEGA(ID)
);

CREATE TABLE FACTURA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE,
    CEDULA_CLIENTE VARCHAR(10),
    TOTAL FLOAT,
    ID_TIPO_PAGO INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    FOREIGN KEY (ID_TIPO_PAGO) REFERENCES TIPO_PAGO(ID),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID),
	FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE(CEDULA)
);

CREATE TABLE VENTA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VALOR FLOAT,
    FECHA_VENTA DATE,
    CEDULA_CLIENTE VARCHAR(10) NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    ID_FACTURA INT NOT NULL,
    ID_TIPO_PAGO INT NOT NULL,
    FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE(CEDULA),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID),
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID),
    FOREIGN KEY (ID_TIPO_PAGO) REFERENCES TIPO_PAGO(ID)
);

CREATE TABLE COTIZACION(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VALOR FLOAT,
    FECHA_COTIZACION DATE,
    CEDULA_CLIENTE VARCHAR(10) NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE(CEDULA),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID)
);

CREATE TABLE ENTREGA_DOMICILIO(
     ID INT AUTO_INCREMENT PRIMARY KEY,
     FECHA_ENTREGA DATE,
     ESTADO BOOLEAN NOT NULL DEFAULT FALSE,
     ID_VENTA INT NOT NULL,
     ID_REPARTIDOR INT NOT NULL,
     FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID),
     FOREIGN KEY (ID_REPARTIDOR) REFERENCES REPARTIDOR(ID)
);

CREATE TABLE PRODUCTO_LOCAL(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR(30) UNIQUE,
    ID_LOCAL INT NOT NULL,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (NOMBRE_PRODUCTO) REFERENCES PRODUCTO(NOMBRE),
    FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL(ID)
);

CREATE TABLE PRODUCTO_BODEGA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR(30) UNIQUE,
    ID_BODEGA INT NOT NULL,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (NOMBRE_PRODUCTO) REFERENCES PRODUCTO(NOMBRE),
    FOREIGN KEY (ID_BODEGA) REFERENCES BODEGA(ID)
);

CREATE TABLE ENTREGA_LOCAL(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTADO BOOLEAN DEFAULT FALSE,
    FECHA_ENTREGA DATE,
    CANTIDAD_PRODUCTO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_BODEGA INT NOT NULL,
    ID_REPARTIDOR INT NOT NULL,
    ID_LOCAL INT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID),
    FOREIGN KEY (ID_BODEGA) REFERENCES BODEGA(ID)

);

CREATE TABLE PEDIDO_LOCAL(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_ENTREGA DATE,
    ESTADO BOOLEAN DEFAULT FALSE,
    ID_GERENTE INT NOT NULL,
    ID_JEFE_BODEGA INT NOT NULL,
    FOREIGN KEY (ID_GERENTE) REFERENCES GERENTE(ID),
    FOREIGN KEY (ID_JEFE_BODEGA) REFERENCES JEFE_BODEGA(ID)
);

CREATE TABLE CREDITO(

    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(30),
    ID_VENTA INT NOT NULL,
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID)
);


CREATE TABLE VENTA_PRODUCTO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_FACTURA INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    CEDULA_CLIENTE VARCHAR(10) NOT NULL,
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID),
    FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE(CEDULA)
);

CREATE TABLE PRODUCTO_COTIZACION(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_COTIZACION INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    FOREIGN KEY (ID_COTIZACION) REFERENCES COTIZACION(ID),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);


